# Generated by Django 4.2.13 on 2024-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                ("filename", models.CharField(max_length=255)),
                (
                    "uuid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "database_json",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "details",
            },
        ),
        migrations.CreateModel(
            name="SubTable",
            fields=[
                (
                    "doc_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("s3_file", models.TextField(blank=True, null=True)),
                ("local_file", models.TextField(blank=True, null=True)),
                ("inserted_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "SubTable",
                "ordering": ["-inserted_time"],
            },
        ),
    ]
